---

- hosts: localhost 
  roles:
    - stancel.create-digitalocean-droplet

- hosts: new_server
  gather_facts: false
  remote_user: root
  become: true
  become_method: sudo
  tasks:
    - name: Install Python 2.x
      raw: which python || sudo apt-get update && sudo apt-get install -qq -y python-simplejson 
      register: python_check
      changed_when: python_check.stdout is not search('/usr/bin/python')

- hosts: new_server
  roles:
    - stancel.apache-webserver
    - oefenweb.percona-server
    - stancel.setup-mysql-backups
    - stancel.install-bareos-client
    - stancel.install-nagios-client
    - stancel.git-download-suitecrm

- hosts: backups monitoring 
  roles:
    - stancel.add-job-to-bareos-director
    - stancel.add-config-to-nagios-server
    - stancel.restore_bareos_backup

- hosts: new_server
  roles:
    - stancel.restore_db_and_files


